# YAML template
---
default: -p pretty -p html
pretty: --format pretty
progress: --format progress
html: --format html --out=./reports/result.html
json: --format json --out=./reports/result.json

# configuração do ambiente, aqui normalmente eu deixo predefinido os ambiente de HOMOLOGAÇÃO ou PRODUÇÃO
# mas como estamos trabalhando somente com produção, deixei sem ambientes
